apiVersion: v1
kind: Secret
metadata:
  name: expensetracker-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://aditidb:aditi123@cluster0.v4jyrfg.mongodb.net/?appName=Cluster0"
  JWT_SECRET: "expense_tracker_super_secret_key_2024_xK9mP2"
